Repository MZero-Labs/ttg, pull requests merged in 2024-04, with the labels that each got.

#257 feat: `getDistributable`
  src/DistributionVault.sol
  src/interfaces/IDistributionVault.sol
  test/DistributionVault.t.sol
  test/utils/DistributionVaultHarness.sol
Labels: enhancement, ready to merge

#264 feat: ERC20 event compliance
  src/abstract/EpochBasedInflationaryVoteToken.sol
  test/EpochBasedInflationaryVoteToken.t.sol
  test/PowerToken.t.sol
Labels: enhancement, ready to merge

#265 Add certora verification rules
  .github/workflows/certora_verification.yml
  .gitignore
  certora/Makefile
  certora/applyHarness.patch
  certora/confs/PowerToken.conf
  certora/confs/StandardGovernor.conf
  certora/confs/ZeroToken.conf
  certora/harness/PowerTokenHarness.sol
  certora/harness/ZeroTokenHarness.sol
  certora/munge.sh
  certora/specs/ERC20Helper.spec
  certora/specs/PowerToken/PowerToken.spec
  certora/specs/PowerToken/setup.spec
  certora/specs/StandardGovernor/PowerTokenMock.spec
  certora/specs/StandardGovernor/StandardGovernor.spec
  certora/specs/StandardGovernor/setup.spec
  certora/specs/VoteTokenStorageMirror.spec
  certora/specs/ZeroToken/ZeroToken.spec
  certora/specs/ZeroToken/setup.spec
  certora/specs/ZeroToken/unsafeAccess.spec
Labels: ready to merge, tests

#270 feat: add `token` to `IGovernor`
  src/PowerToken.sol
  src/ZeroToken.sol
  src/abstract/BatchGovernor.sol
  src/abstract/interfaces/IGovernor.sol
  test/EmergencyGovernor.t.sol
  test/StandardGovernor.t.sol
  test/ZeroGovernor.t.sol
Labels: enhancement

#269 feat: governor standardization
  certora/specs/StandardGovernor/setup.spec
  src/PowerToken.sol
  src/StandardGovernor.sol
  src/ZeroToken.sol
  src/abstract/BatchGovernor.sol
  src/abstract/ThresholdGovernor.sol
  src/abstract/interfaces/IBatchGovernor.sol
  src/abstract/interfaces/IGovernor.sol
  src/abstract/interfaces/IThresholdGovernor.sol
  src/interfaces/IStandardGovernor.sol
  test/BatchGovernor.t.sol
  test/EmergencyGovernor.t.sol
  test/StandardGovernor.t.sol
  test/ZeroGovernor.t.sol
  test/fuzz/EmergencyGovernorDeployerFuzz.t.sol
  test/fuzz/PowerTokenFuzz.t.sol
  test/integration/emergency-governor/propose/emergencyGovernorPropose.t.sol
  test/integration/inflation-rewards/powerInflationZeroRewards.t.sol
  test/integration/standard-governor/propose/standardGovernorPropose.t.sol
  test/integration/zero-governor/propose/zeroGovernorPropose.t.sol
  test/integration/zero-governor/reset/reset-to-power-holders/resetToPowerHolders.t.sol
  test/integration/zero-governor/reset/reset-to-zero-holders/resetToZeroHolders.t.sol
  test/integration/zero-governor/set-thresholds/setZeroEmergencyThresholds.t.sol
  test/utils/BatchGovernorHarness.sol
  test/utils/StandardGovernorHarness.sol
  test/utils/ZeroGovernorHarness.sol
Labels: enhancement

#268 feat: Deployment getters and tests
  .env.example
  script/DeployBase.sol
  test/Deploy.t.sol
Labels: enhancement

#272 feat: `CLOCK_MODE` for external clock computation
  src/DistributionVault.sol
  src/Registrar.sol
  src/abstract/BatchGovernor.sol
  src/abstract/EpochBasedVoteToken.sol
  src/libs/PureEpochs.sol
  test/DistributionVault.t.sol
Labels: enhancement
